### ISSUE TITLE
Sending "q" key value exits app

### ISSUE THREAD

**Issue by tpozzy** [k5md/M2KB#1]
I am trying to use m2kb to map MIDI message from a USB controller (Looptimus) to a golf simulation application on my Windows laptop. I need to send at least "q", "e", "x" and "z" keystrokes. When I map a key to "q" and send the MIDI code, the application terminates. Is there any way to get it to pass "q" on instead of quitting, without modifying the source? It doesn't look like it.

I tried to modify the source, but the build instructions are complete. Installing Docker for Windows and typing "make build" says "Command not found". I think there are some steps missing from the instructions.

**Comment by k5md** [comment]
Hi, thanks, I've updated the repo and issued a new version. Sorry for it taking so long, as you can see, I had to trace first curses.h not found issue (in new ubuntu images), then auth issue, since it has been long time since this project has been published.
>I tried to modify the source, but the build instructions are complete. Installing Docker for Windows and typing "make build" says "Command not found". I think there are some steps missing from the instructions.

It is presupposed that you're running a Linux distribution, then it is as simple as that. For windows, however, it could be more problematic, since you most likely don't have make and bash, you have to replicate steps under build in Makefile.

**Comment by tpozzy** [comment]
Thank you so much for the quick update! And you are correct, I was trying to run Docker in Windows. I was running under Visual Studio Code, and almost had it working. I got the same error on "curses.h".
I am interested in being able to work with Docker for this type of build, so I think I'm going to continue trying to get it running on my system. In the meantime, I will take the updated executable from your latest build.
-Theo  

    On Thursday, January 14, 2021, 02:47:50 AM PST, k5md <notifications@github.com> wrote:  
 
 


Hi, thanks, I've updated the repo and issued a new version. Sorry for it taking so long, as you can see, I had to trace first curses.h not found issue (in new ubuntu images), then auth issue, since it has been long time since this project has been published.


I tried to modify the source, but the build instructions are complete. Installing Docker for Windows and typing "make build" says "Command not found". I think there are some steps missing from the instructions.


It is pressuposed that you're running a Linux distribution, then it is as simple as that. For windows, however, it could be more problematic, since you most likely don't have make and bash, you have to replicate steps under build in Makefile.

**Comment by k5md** [comment]
>I am interested in being able to work with Docker for this type of build, so I think I'm going to continue trying to get it running on my system.

To hopefully save you some time, I can describe the (maybe ridiculous) way I used to build it on Windows 7. Docker does not support it, so only (now deprecated) [Docker Toolbox](https://github.com/docker/toolbox/releases) is available for this OS.

1. Have [git](https://desktop.github.com/) installed and Docker toolbox installed.
2. Clone the repo.
3. Inside create a file with commands from Makefile build, let's call the file "buildProject":
`docker build -t build-mingw-w64 .`
`mkdir ./bin`
`docker create --name dummy build-mingw-w64 bash`
`docker cp dummy:/app/bin .`
`docker rm -fv dummy`
4. Create a .bat file that we will use to trigger build with the following content, with your paths to git and docker toolbox installation directories:
`"FULL_PATH_TO_GIT\bin\bash.exe" --login -i "FULL_PATH_TO_DOCKER_TOOLBOX\start.sh" < buildProject`
`copy lib\*.dll bin\`

I hope, this will help you to make it build under Windows. As a note, I've chosen the docker way of building to ensure it will be easy to compile/crosscompile and autopublish new versions with travis-ci.
