### ISSUE TITLE
Output isn't flushed before asking if user wants to reassign keys

### ISSUE THREAD

**Issue by fchorney** [k5md/M2KB#2]
I'm having an issue where after I choose my MIDI device, the output print statements don't seem to flush before it asks me if I want to reassign.

Basically when I hit `1` on the MIDI device selection, I don't see any new text or indication that anything happened by making that selection.

If I hit `1` and then `shift+y` then it will let me reconfigure the keybinds. Perhaps you need to throw in a print flush in there somewhere?

**Comment by fchorney** [comment]
also slightly unrelated but so small I didn't think I needed to make another issue. This program should accept both lowercase and upper case `y`. It's a little confusing that it doesn't, since a user might hit lowercase y and be confused as to why it's not letting them remap keys

**Comment by k5md** [comment]
Hello, @fchorney !
Thanks for noticing the issue with multiple devices selection! I've just released [new version](https://github.com/k5md/M2KB/releases/tag/v0.1.2-beta) where it seems working fine.

**Comment by fchorney** [comment]
Yes this works perfect now. 
Thanks!!
